// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/:locale?/:shopid/orders/:token/authenticate': {
    params: {
      locale?: string;
      shopid: string;
      token: string;
    };
  };
  '/:locale?/collections/:collectionHandle': {
    params: {
      locale?: string;
      collectionHandle: string;
    };
  };
  '/:locale?/products/:productHandle': {
    params: {
      locale?: string;
      productHandle: string;
    };
  };
  '/:locale?/journal/:journalHandle': {
    params: {
      locale?: string;
      journalHandle: string;
    };
  };
  '/:locale?/policies/:policyHandle': {
    params: {
      locale?: string;
      policyHandle: string;
    };
  };
  '/:locale?/account/authorize': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/collections': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/featured-products': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/pages/:pageHandle': {
    params: {
      locale?: string;
      pageHandle: string;
    };
  };
  '/:locale?/account/logout': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/collections/all': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/policies': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/products': {
    params: {
      locale?: string;
    };
  };
  '/sitemap/:type/:page.xml': {
    params: {
      type: string;
      page: string;
    };
  };
  '/:locale?/account/login': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/discount/:code': {
    params: {
      locale?: string;
      code: string;
    };
  };
  '/:locale?/journal': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/api/countries': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/api/products': {
    params: {
      locale?: string;
    };
  };
  '/sitemap-empty.xml': {
    params: {};
  };
  '/:locale?/account': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/account/address/:id': {
    params: {
      locale?: string;
      id: string;
    };
  };
  '/:locale?/account/orders/:id': {
    params: {
      locale?: string;
      id: string;
    };
  };
  '/:locale?/account/edit': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/account/*': {
    params: {
      locale?: string;
      '*': string;
    };
  };
  '/:locale?': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/search': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/cart': {
    params: {
      locale?: string;
    };
  };
  '/:locale?/cart/:lines': {
    params: {
      locale?: string;
      lines: string;
    };
  };
  '/sitemap.xml': {
    params: {};
  };
  '/robots.txt': {
    params: {};
  };
  '/*': {
    params: {
      '*': string;
    };
  };
  '/graphiql': {
    params: {};
  };
  '/subrequest-profiler': {
    params: {};
  };
  '/.well-known/appspecific/com.chrome.devtools.json': {
    params: {};
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page:
      | '/'
      | '/:locale?/:shopid/orders/:token/authenticate'
      | '/:locale?/collections/:collectionHandle'
      | '/:locale?/products/:productHandle'
      | '/:locale?/journal/:journalHandle'
      | '/:locale?/policies/:policyHandle'
      | '/:locale?/account/authorize'
      | '/:locale?/collections'
      | '/:locale?/featured-products'
      | '/:locale?/pages/:pageHandle'
      | '/:locale?/account/logout'
      | '/:locale?/collections/all'
      | '/:locale?/policies'
      | '/:locale?/products'
      | '/sitemap/:type/:page.xml'
      | '/:locale?/account/login'
      | '/:locale?/discount/:code'
      | '/:locale?/journal'
      | '/:locale?/api/countries'
      | '/:locale?/api/products'
      | '/sitemap-empty.xml'
      | '/:locale?/account'
      | '/:locale?/account/address/:id'
      | '/:locale?/account/orders/:id'
      | '/:locale?/account/edit'
      | '/:locale?/account/*'
      | '/:locale?'
      | '/:locale?/search'
      | '/:locale?/cart'
      | '/:locale?/cart/:lines'
      | '/sitemap.xml'
      | '/robots.txt'
      | '/*'
      | '/graphiql'
      | '/subrequest-profiler'
      | '/.well-known/appspecific/com.chrome.devtools.json';
  };
  'routes/($locale).$shopid.orders.$token.authenticate.tsx': {
    id: 'routes/($locale).$shopid.orders.$token.authenticate';
    page: '/:locale?/:shopid/orders/:token/authenticate';
  };
  'routes/($locale).collections.$collectionHandle.tsx': {
    id: 'routes/($locale).collections.$collectionHandle';
    page: '/:locale?/collections/:collectionHandle';
  };
  'routes/($locale).products.$productHandle.tsx': {
    id: 'routes/($locale).products.$productHandle';
    page: '/:locale?/products/:productHandle';
  };
  'routes/($locale).journal.$journalHandle.tsx': {
    id: 'routes/($locale).journal.$journalHandle';
    page: '/:locale?/journal/:journalHandle';
  };
  'routes/($locale).policies.$policyHandle.tsx': {
    id: 'routes/($locale).policies.$policyHandle';
    page: '/:locale?/policies/:policyHandle';
  };
  'routes/($locale).account_.authorize.ts': {
    id: 'routes/($locale).account_.authorize';
    page: '/:locale?/account/authorize';
  };
  'routes/($locale).collections._index.tsx': {
    id: 'routes/($locale).collections._index';
    page: '/:locale?/collections';
  };
  'routes/($locale).featured-products.tsx': {
    id: 'routes/($locale).featured-products';
    page: '/:locale?/featured-products';
  };
  'routes/($locale).pages.$pageHandle.tsx': {
    id: 'routes/($locale).pages.$pageHandle';
    page: '/:locale?/pages/:pageHandle';
  };
  'routes/($locale).account_.logout.ts': {
    id: 'routes/($locale).account_.logout';
    page: '/:locale?/account/logout';
  };
  'routes/($locale).collections.all.tsx': {
    id: 'routes/($locale).collections.all';
    page: '/:locale?/collections/all';
  };
  'routes/($locale).policies._index.tsx': {
    id: 'routes/($locale).policies._index';
    page: '/:locale?/policies';
  };
  'routes/($locale).products._index.tsx': {
    id: 'routes/($locale).products._index';
    page: '/:locale?/products';
  };
  'routes/sitemap.$type.$page[.xml].tsx': {
    id: 'routes/sitemap.$type.$page[.xml]';
    page: '/sitemap/:type/:page.xml';
  };
  'routes/($locale).account_.login.tsx': {
    id: 'routes/($locale).account_.login';
    page: '/:locale?/account/login';
  };
  'routes/($locale).discount.$code.tsx': {
    id: 'routes/($locale).discount.$code';
    page: '/:locale?/discount/:code';
  };
  'routes/($locale).journal._index.tsx': {
    id: 'routes/($locale).journal._index';
    page: '/:locale?/journal';
  };
  'routes/($locale).api.countries.tsx': {
    id: 'routes/($locale).api.countries';
    page: '/:locale?/api/countries';
  };
  'routes/($locale).api.products.tsx': {
    id: 'routes/($locale).api.products';
    page: '/:locale?/api/products';
  };
  'routes/[sitemap-empty.xml].tsx': {
    id: 'routes/[sitemap-empty.xml]';
    page: '/sitemap-empty.xml';
  };
  'routes/($locale).account.tsx': {
    id: 'routes/($locale).account';
    page:
      | '/:locale?/account'
      | '/:locale?/account/address/:id'
      | '/:locale?/account/orders/:id'
      | '/:locale?/account/edit'
      | '/:locale?/account/*';
  };
  'routes/($locale).account.address.$id.tsx': {
    id: 'routes/($locale).account.address.$id';
    page: '/:locale?/account/address/:id';
  };
  'routes/($locale).account.orders.$id.tsx': {
    id: 'routes/($locale).account.orders.$id';
    page: '/:locale?/account/orders/:id';
  };
  'routes/($locale).account.edit.tsx': {
    id: 'routes/($locale).account.edit';
    page: '/:locale?/account/edit';
  };
  'routes/($locale).account.$.tsx': {
    id: 'routes/($locale).account.$';
    page: '/:locale?/account/*';
  };
  'routes/($locale)._index.tsx': {
    id: 'routes/($locale)._index';
    page: '/:locale?';
  };
  'routes/($locale).search.tsx': {
    id: 'routes/($locale).search';
    page: '/:locale?/search';
  };
  'routes/($locale).cart.tsx': {
    id: 'routes/($locale).cart';
    page: '/:locale?/cart' | '/:locale?/cart/:lines';
  };
  'routes/($locale).cart.$lines.tsx': {
    id: 'routes/($locale).cart.$lines';
    page: '/:locale?/cart/:lines';
  };
  'routes/[sitemap.xml].tsx': {
    id: 'routes/[sitemap.xml]';
    page: '/sitemap.xml';
  };
  'routes/[robots.txt].tsx': {
    id: 'routes/[robots.txt]';
    page: '/robots.txt';
  };
  'routes/$.tsx': {
    id: 'routes/$';
    page: '/*';
  };
  '../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx': {
    id: '/Users/reisscashmore/Development/hydrogen-demo-store/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout';
    page:
      | '/graphiql'
      | '/subrequest-profiler'
      | '/.well-known/appspecific/com.chrome.devtools.json'
      | '/';
  };
  '../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx': {
    id: 'vite/virtual-routes/routes/graphiql';
    page: '/graphiql';
  };
  '../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx': {
    id: 'vite/virtual-routes/routes/subrequest-profiler';
    page: '/subrequest-profiler';
  };
  '../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx': {
    id: 'vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json';
    page: '/.well-known/appspecific/com.chrome.devtools.json';
  };
  '../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx': {
    id: 'vite/virtual-routes/routes/index';
    page: '/';
  };
};
